EyeWitness.py
masscan creates an xml file “inspired by” but not identical to the nmap
xml file. This branch adds support for this format with —createtargets
=> Adding support for parsing masscan xml

CHANGELOG, modules/reporting.py
=> Reportlinks

CHANGELOG, modules/helpers.py
This fixes issue #156.  Thanks to @digininja for bringing this to our attention!
=> createtargets correctly parses all services

EyeWitness.py, modules/helpers.py
Hi Chris, 
Thanks for the work on this; I really appreciate the tool. I often run into instances where there are esoteric ports in an nmap run that I know are HTTP/HTTPS, but nmap doesn't flag the service and so Eyewitness doesn't pick them up. It's simple enough to edit http_ports in helpers, but here's a patch to support it from the command line if you're interested. 
It adds support for two more arguments:
```
--add-http-ports ADD_HTTP_PORTS
Additional port(s) to assume are http
--add-https-ports ADD_HTTPS_PORTS
Additional port(s) to assume are https
```
Example usage (redacted from a real use, please pardon any inconsistencies in the results):
```
$ ./EyeWitness.py --web -f ~/tmp/nmap_ext_example.xml --createtargets eyewitness_targets.txt --add-http-ports 8018 --add-http-ports 8028 …
```
=> add support for additional http/https ports on command line

modules/selenium_module.py
Took me a while to find out that I just needed to apt-get install firefox, because the error was saying 'Unknown error' - when I made this change it said that it couldn't find firefox. Installing firefox fixed the problem :D
=> Throw errors that are actionable

categories.txt, signatures.txt
=> Fixed bug due to bad record format in categories file

EyeWitness.py, modules/helpers.py
This pull-request converts EyeWitness from DOM to SAX xml parsing.
=> Convert XML Parsing

EyeWitness.py, dataFile.txt, modules/db_manager.py, modules/helpers.py, modules/login_module.py, modules/objects.py, modules/reporting.py, setup/setup.sh
Merge in @chango77747's changes to allow active scanning.
=> Activeauth

EyeWitness.py, modules/helpers.py
This adds in the functionality requested in issue #199
=> Select ports

dataFile.txt
Added the url path for phpmyadmin.
=> Missed url_path for PHPMyAdmin

setup/setup.sh
Updated OS check to support Kali Rolling.
=> Support for Kali2 and Rolling

setup/setup.sh
=> Added update for geckodriver on ubuntu

EyeWitness.py, modules/phantomjs_module.py, modules/selenium_module.py
I've added socks proxy support for the selenium and Phantom modules.
It's can be used if you have to pivot through another server.
=> Added Socks proxy support

Dockerfile, README.md
1. I added a Dockerfile in order to create a isolated environment for EyeWitness.
2. I edited the README.md:
- I've Beautify it in order to be more convenient to read
- I've add a Docker section
P.S. Its my first pull request ever :)
=> Add a Dockerfile and beautify README.md

Dockerfile
=> fix for Docker file

modules/reporting.py
If we include bootstrap css and modify the table class to "table", we end up with a report easier on the eyes.
=> Make EyeWitness reports pretty!

modules/login_module.py
Added the "html.parser" option to the BeautifulSoup call to suppress that annoying message popping out every other request.
=> modified:   login_module.py

setup/setup.sh
Thanks to Michael Kramer for the OCR submission!
=> Prep for ocr stuff

EyeWitness.py, modules/rdp_module.py
I added a very basic idea of using OCR to determine the usernames within a RDP screenshot.
For this to work Tesseract-OCR must be installed (Best working version is 4.0)
Compiling manual is found at https://github.com/tesseract-ocr/tesseract/wiki/Compiling
Also pytesseract 0.1.6 (pip install pytesseract) is needed for this to work.
The basic idea is to check the pixel at (10, width-10) and compare the colorvalue to a list I've added (which right now only consists of my testsystems and might need further testing/adding of more values) to determine which operating system is running and how to crop the image to only display the username for the OCR to read.
The function adds three files in the report depository. domains.txt tries to contain all domains found, users.txt contains usernames …
=> Added first version of OCR

modules/helpers.py
Extra csv called open_ports.csv is included in report folder, contains csv of all open ports, all hosts, and correlates everything
=> Added csv file outputting open ports

setup/setup.sh
Ubuntu install was broken due to missing packages.
=> Add missing packages

README.md
this enables copy and paste ;-)
=> missing backslash in examples

Dockerfile
Set default value for user ARG in the Dockerfile. I set the value to eyewitness
=> [Dockerfile] Default value for user ARG

modules/phantomjs_module.py, modules/selenium_module.py
=> Fixed error where file is too long with a long URL, skips the URL

modules/helpers.py
This expands on #383 and shows the URL where the potential error is
=> Error now shows URL where there is a possible issue

modules/helpers.py
This function will detect identical screenshots and delete all copies except one.
Therefore it opens all HTML report files and replaces the individual file paths by the single one that is kept.
The current algorithm, for each case of identical files, will read all report files, replace the file name in the content, then write the result. This is not very efficient since:
* The same report files are read several times
* All report files are overwritten every time, even if they were not modified
My PR proposes to read all files once at the beginning and keep them in memory. Moreover, they are overwritten only if their content changes. They are still written at each loop iteration, which is not the most efficient algorithm, but it is better reliable in case of an interrupt and later resume. …
=> Increase performance for duplicate_check

setup/setup.sh
tested on Manjaro Juhraya 18.1.0 and it's working fine
=> added support for arch or manjaro based distro

.gitignore, EyeWitness.py, README.md, modules/selenium_module.py
**Feature**:
- Add support for http and socks5 proxy
- Ignore '*.log' file in .gitignore
- Add example in README.md
Link to issue : https://github.com/FortyNorthSecurity/EyeWitness/issues/436
=> Add proxy (http/socks5) support

modules/reporting.py
Add right/left arrow key click on the next/previous links. Found it a bit easier than tabbing to links or lots of hunting for the "next" hyperlink
=> Add arrow key navigation for next/previous pages

Dockerfile, setup/setup.sh
Updating references in setup and dockerfile to migrate the docker image to python3. Also fixed some minor warning bugs and updated the gecko driver.
=> Fixing docker image for python3

EyeWitness.py, modules/helpers.py, modules/selenium_module.py
These changements have been done to add a delay between the opening of the navigator and taking the screenshot; this could be usefull in the case of single page app and others ....
=> Delay screenshot

EyeWitness.py, modules/db_manager.py
Not used and a pain to support
=> Removed user agent cycling option

Dockerfile
I have created issue #450 which shows the error this PR fixes.
=> Updated git url in Dockerfile

Python/Dockerfile
Hi,
Yesterday i try to setup eyewitness with Dockerfile but unfortunately fail.
So I'm just make litle bit change in Dockerfile and everything run pretty fine.
And i want to share my change, maybe it can help others.
Thank you
=> Fix missing dockerfile syntax

Python/setup/setup.sh
replaced geckodriver 64 and 32 links by their global variables
=> replaced geckodriver 64 and 32 links by their global variables

Python/setup/setup.sh
Added checking os Alpine Linux. And added installation of dependencies for Alpine.
=> Installing Alpine dependencies

Python/modules/reporting.py
This could probably be styled a bit nicer, but it will show the current page number at the top and bottom of the report page so you know where you are when there are loads of pages.
=> show current page number

Python/signatures.txt
I don't know why the last line is flagged as changed as well, I only made the one change in the GitHub editor.
=> admin not dmin

Python/setup/setup.sh
Issue https://github.com/FortyNorthSecurity/EyeWitness/issues/563
=> Check files exist before reading them.

Python/MiktoList.py, Python/Recategorize.py, Python/Search.py, Python/modules/helpers.py
replace deprecated distutils strtobool by replacing with strtobool in helpers.py
issue #576
=> strtoboolreplace - replace deprecated distutils

Python/Recategorize.py
Updated recategorize.py for python3
=> update recategorize.py for python3

Python/categories.txt, Python/signatures.txt
=> additional signatures -relkci jan 23

Python/EyeWitness.py, Python/modules/selenium_module.py
Hello there!
Your project is really great, I searched for such instrument for a long time.
For my needs I needed to pass cookie headers in request, so I hope this option could be good for project too.
Feel free to ask for updates fixes and extra ideas.
What was done:
- Added cookie option to argparse
- Cookies add during request
- Tested on bwapp
=> Add cookie option 

Python/EyeWitness.py
=> typo and new line to highlight the error message

CS/EyeWitness/Program.cs
category name on C# is incorrect -- emptyu / empty
=> wrong category name

Python/EyeWitness.py, Python/modules/helpers.py
added option to not clear buffer 
addresses #552
=> option to not clear buffer 

CS/EyeWitness/Program.cs, Python/categories.txt, Python/modules/reporting.py
Correct some incorrect categories and add missing virtualization category
printers -> printer
invalidreq -> badreq
redirect -> redirector
add virtualization category
vm -> virtualization
=> Category fixes

Python/categories.txt, Python/signatures.txt
Looks like I don't have commit access or I'd merge this in
Updated signature added to text files
=> Updated Signatures

Python/modules/reporting.py
Add the following columns to Requests.csv:
- Title
- Resolved host
- Category
- Default Creds
Addresses #621 #503 and #637
=> Add Title, Resolved host, Category, Creds to Requests.csv

Python/categories.txt, Python/signatures.txt
=> Signatures

.travis.yml
remove deprecated .travis.yml travis CICD reference
addresses #653
=> remove  .travis.yml

Python/categories.txt, Python/signatures.txt
Add device signatures and categories
=> add devices

Python/categories.txt, Python/signatures.txt
added:
* Ubiquiti wireless access point + default cred
* Star printer TSP100III + default cred
* DVR IP Camera + default cred
* Secondary Hikvision IP camera signatures
* Quantum Spark Security Firewall + default cred
* Secondary Cisco SSL VPN category detection
Tested and working.
@Relkci
=> Updated Categories and Signatures
