RedSiege/EyeWitness

EyeWitness.py
modules/helpers.py

adds in --prepend-https option which adds both http:// and https:// to the front of URLs which don't have either in the URL.

Proposed addition for issue #165

---

EyeWitness.py

This will prevent a proxy IP being used without a port, and vice-versa.
It appears that if just an IP was provided, it would ignore the proxy and take a screenshot anyways.
Should help address issue #171

Added check for proxy port and ip

---

EyeWitness.py
modules/phantomjs_module.py

Hi,
in cases where one is trying to run eyewitness against an IP that serves multiple virtual hosts, being able to set the Host header is useful to request a specific virtual host. While normally you'd expect DNS to be set up correctly, where this is not the case, one needs to run against the IP and specify a Host explicitly. This PR allows that in single+headless mode, as phantomjs makes it straightforward, so submitting this for inclusion

Add ability to specify hostname in Host header for phantomjs/single mode

---

modules/helpers.py

This re-enables the ability to specify http or https ports when parsing XML to look for.  This was accidentally removed when adding in the new XML parsing "feature".

Added in ability to add http(s) ports to look for, accidentally removed it

---

CHANGELOG
setup/setup.sh

This fixes issue #220 and places the geckodriver in /usr/sbin during the setup process.  In testing, this only seems to impact Kali.

Fix for Geckodriver

---

CHANGELOG
EyeWitness.py
modules/phantomjs_module.py
modules/selenium_module.py

This adds in a feature from issue #225.  This pull request allows users to specify the max amount of retries for each website that hit the timeout limit while EyeWitness was trying to screenshot it.
This only applied to websites (not RDP or VNC).

Added in ability to specify max retries

---

EyeWitness.py

Elements in the "http_ports" and "https_ports" lists have to be strings. Otherwise the additionally added ports are ignored when parsing .nessus files.

fixed "http_ports" and "https_ports" list elements

---

EyeWitness.py
modules/helpers.py

This removes duplicate images after a report is generated.  Right now, this does not happen on resumes, I've encountered odd issues where resuming causes pictures to be missing.  Therefore this is only in effect when scanning using file input (text or xml) and not resuming a scan.
It does remove all images with the same md5 hash, even if across multiple pages in the report.

Removes duplicate images as suggested in issue #245

---

modules/helpers.py

no-prompt with -d overwrites directory

---

setup/setup.sh

Currently the setup script uses `/etc/issue` to check the OS version for Kali indicators. This isn't very robust and breaks if `/etc/issue` is customized. Using `lsb_release` to perform this check is more reliable, and if that fails falling back to `/etc/os-release` works as well. This could be further improved by removing the `if` block entirely and modifying the `case` block to use expected outputs of `lsb_release`.

Improve osinfo resolution to use standard lsb_release

---

EyeWitness.py
setup/setup.sh

In my changes I've removed the hard-coded path check for "./bin/phantomjs" so EyeWitness can be executed from anywhere. 
Also, the setup script was complaining of a non-existing directory "../bin" when running it as `sudo ./setup/setup.sh`. In my change I save the current directory, `cd` into the directory where the script is living and run it from there.

remove hard-coded paths

---

modules/reporting.py

I personally think it's better to save in the field domain the domain without the port if it's specified.
Before, the domain (if set with a port in the input list) was looking like this (for "google.com:8000"):
`Protocol,Port,Domain,Request Status,Screenshot Path, Source Path
http,8000,google.com:8000,ConnRefuse,/tmp/output/screens/http.google.com.8000.png,/tmp/output/source/http.google.com.8000.txt`
With this small change, the port is stripped out of the "domain" column:
`Protocol,Port,Domain,Request Status,Screenshot Path, Source Path
http,8000,google.com,ConnRefuse,/tmp/output/screens/http.google.com.8000.png,/tmp/output/source/http.google.com.8000.txt`

Small fix for the logging of the hostname

---

CHANGELOG
modules/objects.py
modules/reporting.py

This pull request's goal is to make sure that Unicode encoding errors in `objects.py` and `reporting.py` are caught and dealt with. 
---
For any html doc that has weird Unicode characters, you can decode it fine, but after the sanitation process (exhibited in `objects.py`) you cannot store it in a variable as a non-Unicode string. In fixing this problem a new problem arose, you couldn't write non-Unicode encoded strings to files. This is fixed by excepting the `UnicodeEncodeError` and writing instead as an encoded string.

Exceptions for unusual Unicode characters

---

setup/setup.sh

Parrot OS 4 and above seems to satisfy the same prerequisites as Kali Rolling.
Test on ParrotOS 4.2
As ParrotOS is now gaining ground as a common alternative for web application penetration testing I think it would be ideal to allow support for it.
Regards

Support for ParrotOS 4

---

Dockerfile

Eyewitness was complaining and the provided docker examples aren't working due to the lack of directory.

Added mkdir tmp\EyeWitness 

---

EyeWitness.py
setup/setup.sh

This pull request removes the "--headless" option from the command line menu. The only web option will now be --web. The --web parameter runs firefox, but it also runs it headlessly.
If on a server, you will need to install firefox, but then it will run headlessly.

Headless Update

---

setup/setup.sh

Fixed Centos detection #399
Previously setup.py would return the following :
```
#######################################################################
#######################################################################
Error]: \S is not supported by this setup script.
```
Now setup.py detects Centos and proceeds to the CentOs code block correctly.
```
#######################################################################
#######################################################################
[*] Centos detected
[Warning]: EyeWitness on CentOS Requires EPEL Repository!
[?] Install and Enable EPEL Repository? (y/n): 
```

fixed CentOS detection 399

---

setup/setup.sh

In CentOS section of setup.sh
- added pyton-devel package to yum install  (python-dev existed but this is not a valid yum package, fixed #401 )
- Replaced incorrect yum packages with the correct yum packages xorg-x11-server-Xvfb, tesseract, firefox (fixes #403)
```
Transaction Summary
=======================================================================================================================================
Install  3 Packages (+38 Dependent packages)
Total download size: 134 M
Installed size: 346 M
Is this ok [y/d/N]: y
...
Installed:
firefox.x86_64 0:60.7.0-1.el7.centos      tesseract.x86_64 0:3.04.00-3.el7      xorg-x11-server-Xvfb.x86_64 0:1.20.1-5.3.el7_6
Dependency Installed:
adwaita-cursor-theme.noarch 0:3.28.0-1.el7                        adwaita-icon-theme.noarch …
```

CentOS : added python-devel to yum install fixes #401

---

setup/setup.sh

Without this, you get this error on boxes which aren't Redhat when running the setup script.
```
grep: /etc/redhat-release: No such file or directory
```

check if redhat release file exists before grepping it in setup script

---

modules/selenium_module.py

In some cases, the driver raises an exception (which seems to come from Firefox's Marionnette according to the error message "curContainer.frame.document.documentElement is null") which is not captured.
It makes the current worker process dies, which is annoying when using the threads option, since the screenshotting continues, but with less processes...
My suggestion is to capture it and continue anyway.
Full error stacktrace:
```
Attempting to screenshot http://<redacted>
Process Process-6:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "EyeWitness/EyeWitness.py", line 337, in worker_thread …
```

Add handling for WebDriverException

---

README.md

The Dockerfile has been moved to a different directory (`./Python`)
I updated the command so users can execute it from within the root folder.

Update docker build command in README.md

---

setup/setup.sh

The setup script in its current form does not distinguish pip against which python version packages are being installed for. In the case of Python2 branch, they should target `pip2` or `python2 -m pip`
The current implementation causes packages to be installed for whatever python version the user's local `pip` instance defaults. Usually this would be python2, but this is likely not going to be the case for long since python2 is deprecated, and pipy is following suit. In my case, `pip` targets python3.6, so it installed the dependencies for python3, but not python2 which is what I was trying to use.
It is better to be explicit and install via `python2 -m pip install` so that users aren't sent on a wild goose-chase trying to figure out why the EyeWitness.py script insists that packages are …

Python2 Setup Method Updates

---

Python/setup/setup.sh

This simple PR fixes empty spaces in geckodriver variables declaration that give invalid url error (as the variable is not filled because of the space) during wget command: 
``` 
Try `wget --help' for more options.
tar: geckodriver-v0.26.0-linux64.tar.gz: Cannot open: No such file or directory
```

Fixed geckodriver variables

---

Python/EyeWitness.py
Python/modules/selenium_module.py

**Feature**:
- Add `--selenium-log-path` in Eyewitness CLI to handle Selenium geckodriver logs. For instance, they can be redirected to `/dev/null` if they are unwanted.
If I didn't respect some of your code requirements, be free to notice me.

Add --selenium-log-path argument to handle Selenium geckodriver logs

---

README.md

Clarify README.md so that it's more clear that the setup directory is
found in the Python directory.

Clarify setup path for Linux

---

Python/Dockerfile

Appended platform-specific `:master-amd64` to the `FROM` line to get around build error (see below).
**Docker** warning:
```
$ sudo docker build -t fortynorthsecurity/eyewitness:latest .
Sending build context to Docker daemon  881.2kB
Step 1/11 : FROM phusion/baseimage
manifest for phusion/baseimage:latest not found: manifest unknown: manifest unknown
```
**VMware vctl** warning:
```
WARNING error in base image preparation: error while checking base image and local storage: failed to get the digest of image phusion/baseimage: GET https://index.docker.io/v2/phusion/baseimage/manifests/latest: MANIFEST_UNKNOWN: manifest unknown; map[Name:phusion/baseimage Revision:sha256:29479c37fcb28089eddd6619deed43bcdbcccf2185369e0199cc51a5ec78991b]; base images will be fetched from remote registry
``` …

Update Dockerfile FROM line

---

Python/modules/reporting.py

sort_data_and_write() had insufficient type checks in pre-filter lambda.
Fix by defining a pre-filter sorting function with more thorough checks.
Should also fix #483

Fix sort_data_and_write type error

---

Python/modules/helpers.py

Here is an example XML output from Nmap for an HTTPS service on port 444:
```xml
<port protocol="tcp" portid="444">
<service name="http" product="Microsoft IIS httpd" version="10.0" ostype="Windows" tunnel="ssl" method="probed" conf="10">
</service>
```
With current code, this will generate an "http://" URL instead of "https://"
With this example, in terms of code, we have `attributes['name']` = `"http"` and `"ssl" in attributes['tunnel']` = `True`
With the current code, we have `elif "http" == attributes['name'] or self.port_number in self.http_ports:` that comes first and immediately returns "http" before the check of the "tunnel" attribute can happen.
So I moved it before :)

Fix HTTPS service detection in Nmap XML

---

CS/EyeWitness/Program.cs
CS/EyeWitness/WitnessedServer.cs

I had some bugs where the task would time out even though it was just started.
The changes in here mainly fix the order of acquiring the lock/semaphore before creating the cancellationToken. This also allowed to do the source code grabbing asynchronously as well.
There is some extra code in there that allows to pass domains to the tool instead of only URLs. I hope this is also a worthy addition.

Improvements on the asynchronous code

---

CS/EyeWitness/Program.cs

Force TLS v1.2 and add better exception logging for this problem

Fix for #471 "the windows client can't fire up" -  Force TLS v1.2

---

Python/modules/objects.py

Sorry this took me so long! It's been a crazy year all around...
Closes #520 
Allows for the manual completion of EyeWitness scans via sqlite database manipulation. Adding the AttributeError mitigates NoneType exceptions after marking hosts as complete. Had to be added in two places to get working.
Future reference for anybody who stumbles upon this issue (until I or anybody else identifies what causes this issue):
Connect to the database file and run the following query: `UPDATE http SET complete = 1 WHERE complete = 0;`
Resume EyeWitness and the scan should complete.

Add AttributeError exception to allow manual scan completion

---

Python/Dockerfile.el7
Python/Dockerfile.el8
Python/setup/setup.sh
README.md

Hello,
I worked to add setup support for CentOS 7 and Rocky Linux 8 and associated Dockerfile. As such, it can be used standalone by anyone interested but also for testing of the setup process for the two distributions.
I also updated the documentation to reflect this change.
Only point to not adequately set is the maintainer label in both Dockerfile. I currently put ???. You can change it to your convenience.
Hope it can be merge quickly :)
Best regards.

Add setup & docker support for Cent0S 7 and Rocky Linux 8

---

Python/categories.txt
Python/signatures.txt

Newlines for the IBM BladeCenter entries were causing parsing errors in the modules/helper.py script

Fixed IBM BladeCenter categories and signatures file entries

---

CS/EyeWitness/EyeWitness.csproj
CS/EyeWitness/Program.cs
CS/EyeWitness/app.config
CS/EyeWitness/packages.config

This option is super useful but got clobbered by the reversion in c2fbef5c797349eb92b0d17ea0e35f06fbdfc6c8. It looks like when the change was originally added, it was set to target .NET Framework 4.8 when the rest of the project was targeting 4.5. I updated the package configs so that everything runs on 4.5 now and the pipeline should pass 🤞

Adding back the CIDR option 

---

CS/EyeWitness/Program.cs
Python/categories.txt

update Program.cs to account for new categories
correct index array on ln 656

update categories for CS build

---

Python/setup/setup.sh

`pip install` doesn't work on Kali, it wants us to install using apt instead so updating the setup script to do that.
I've tested on a brand new weekly install VM and it worked fine.

Fixing setup for Kali

---

Python/MiktoList.py
Python/Recategorize.py
Python/Search.py
Python/modules/db_manager.py

Closes #427
Updated Search.py, Recategorize.py, and MiktoList.py to be Python3-compatible.
Required changing modules/db_manager.py `search_for_term` function to properly encode str/byte types.
All scripts tested and working on Parrot using Python 3.9.2.
Feedback welcome as always. Thanks folks!

Update tools (Search, Recategorize, MiktoList) to Python3

---

Python/EyeWitness.py

Closes #632.
Adds similar signal handler as `multi_mode` function into `single_mode` function. Does not remove created directory, though I can look at adding that if desirable.
Tested on Parrot Security.

Cleanly Exit Single Mode Upon Ctrl+C

---

Python/setup/requirements.txt
Python/setup/setup.sh

Closes #639. This is the rewritten setup.sh script for the Python version of EyeWitness.
Note that this does not close issue 636. I had naively put in a hack fix to force pip to break system packages but after discussion on that issue, I decided it needed more R&D to determine the best solution. 
Notable changes/features are as follows:
1. Reduced code redundancy
2. Refactored Python dependencies to a requirements.txt file
3. Cleaned up global variables
4. Adjusted how OS version is determined and matched for
5. Cleaned up and improved geckodriver retrieval (closes #635)
1. Removed static geckodriver version in lieu of a call to the GitHub API to get the latest version of geckodriver (closes #601)
- In case this one is controversial: looking back at the geckodriver related issues shows a …

Setup Script Rewrite

---

Python/modules/helpers.py

original #605 from deleted head branch/repo.
Addresses #656 -- maybe.  The example in the issue post from rengine-ng https://github.com/Security-Tools-Alliance/rengine-ng/issues/15 provided a sample URL that itself appeared legitimately malformed with a space in the URL.  For the sake of this MR, I have to assume that was accidental and wasn't the cause of bringing #605 back up.   
The example provided in #605 is fixed by the proposed changes from #605 and now here.
MR #659 addresses not-malformed URL from #605 by acknowledging it is not malformed
```
http://vimeo.com/api/oembed.json?url=/web/20131219172814/http://vimeo.com/80375746&api=1&amp;player_id=preroll&height=354&width=630&callback
```
Screenshot:

Malformed URL (from deleted head 605)

---

Python/EyeWitness.py
Python/modules/objects.py
Python/modules/selenium_module.py

Allows the specification of window width and height.  sets default 1366x768.  The width and height are restricted with logic to prevent unreasonable report generations. 
The report output (HTML generation) has been modified slightly with CSS to prevent an image size shorter than 400 px from improperly scaling the image width beyond reason.  Any image with height less than 400 will retain its original height and scale the width accordingly.   The logic should prevent specifying an image height of less than 400, but since the argument specifies the window size, not image size, a 400 specification will produce an actual image less than 400 tall.
Apologies on the silly commit message, I squashed and didn't realize it retained the last message
closes #584

Specify window (image/screenshot) size

---

Python/bin/style.css
Python/modules/helpers.py
Python/modules/reporting.py

Closes #557 & addresses the missing style.css link.
- Moves style to style.css
- Copies style to report folder
- Links style.css in report html

move stylesheet to file

---

Python/modules/objects.py
Python/modules/selenium_module.py

When a website uses agressive means to bot-check, selenium may properly capture a screenshot, but use of urllib to capture headers/source may stall out (probably on something like a javascript challenge).  Changes below force urllib to timeout according to the timeout argument.  If you do not force urllib to timeout, python can sit indefinitely if there is no fallback env-var timeout for it to use.
closes #667 
The report (objects.py) is also updated to reflect the possibility that a screenshot may have been captured even if urllib was forced into a timeout condition.  The image will be included on the error section of the report, if it exists.  No screenshot is shown if selenium also timed out.  Because no source was captured when urllib is forced into timeout, its not possible to …

handle timeouts from urllib (headers/source)

---

Python/modules/selenium_module.py

Add handling for TypeError and Exception on urllib call in selenium_module.py -- will catch some unhandled exceptions that we don't often see but also cant' easily troubleshoot/explain.  
Also: although this shouldn't be an issue further -- added Exception class error when attempting to encode the source and store it in a variable.  In theory, EyeWitness shouldn't make it to the point that urllib failed and its trying to encode NoneType (source), but if it happens again, EyeWitness shouldn't error/stack trace.
addresses #660 
Tested with typical sample URLs -- though none would create the exception that this MR intends to resolve.

add urllib exception handling

---

Python/categories.txt
Python/signatures.txt

Here's a nuclei template to go with it
```yaml
id: acti-web-configurator-default-login
info:
name: ACTi Web Configurator Default Login
author: mr-pmillz
severity: high
description: ACTi Web Configurator Default Login
reference:
- https://customvideosecurity.com/blog/blog-tag/default-acti-password/#:~:text=Please%20add%20this%20link%20to,Avigilon%3A%20admin%2C
tags: default-credentials,network-camera,camera
http:
- raw:
- |+
GET /cgi-bin/system?USER={{username}}&PWD={{password}}&LOGIN&CHANNEL=1&SYSTEM_INFO HTTP/1.1
Host: {{Hostname}}
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Accept: */*
Content-Type: application/x-www-form-urlencoded
Cookie: User=; Pwd=
Connection: close
payloads:
username:
- admin
- Admin
password:
- 123456
attack: clusterbomb …
```

add camera sigs ✨

---

Python/categories.txt
Python/signatures.txt

tested and verified workin'
Here's a Nuclei template to go with it 💥 
```yaml
id: gw-security-camera-default-login
info:
name: GW Security Camera Default Login
author: mr-pmillz
severity: high
description: GW Security Camera Default Login
reference:
- https://gwsecurityusa.com/wp-content/Firmware/Cameras/50-54-60-80%20Series%20IP%20Cameras/GW50-54-80%20Series%20Quick%20Guide%2020170619.pdf
tags: default-credentials,network-camera,camera
http:
- raw:
- |+
POST /getUserConfig HTTP/1.1
Host: {{Hostname}}
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Accept: text/javascript, text/html, application/xml, text/xml, */*
X-Requested-With: XMLHttpRequest
Content-type: application/x-www-form-urlencoded
Content-Length: 223
Connection: close
Cookie: …
```

added GW Security Camera sigs
